# Generated by Django 4.2.16 on 2025-08-02 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "government_type",
                    models.CharField(
                        choices=[
                            ("LIBERAL_MAJORITY", "Liberal Majority"),
                            ("LIBERAL_MINORITY", "Liberal Minority"),
                            ("CONSERVATIVE_MAJORITY", "Conservative Majority"),
                            ("CONSERVATIVE_MINORITY", "Conservative Minority"),
                            ("COALITION", "Coalition Government"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prime_minister", models.CharField(max_length=100)),
                ("immigration_minister", models.CharField(max_length=100)),
                (
                    "economic_immigration_priority",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "humanitarian_priority",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "francophone_priority",
                    models.IntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PNPActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ON", "Ontario"),
                            ("BC", "British Columbia"),
                            ("AB", "Alberta"),
                            ("SK", "Saskatchewan"),
                            ("MB", "Manitoba"),
                            ("NS", "Nova Scotia"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("PE", "Prince Edward Island"),
                            ("YT", "Yukon"),
                            ("NT", "Northwest Territories"),
                            ("NU", "Nunavut"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "invitations_issued",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("minimum_score", models.IntegerField(blank=True, null=True)),
                (
                    "program_stream",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provincial_unemployment", models.FloatField(blank=True, null=True)),
                (
                    "key_sectors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Key economic sectors targeted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "province"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("IMMIGRATION_TARGET", "Immigration Level Target"),
                            ("MINISTER_MANDATE", "Minister Mandate Letter"),
                            ("BUDGET_ANNOUNCEMENT", "Budget/Fiscal Announcement"),
                            ("PROGRAM_CHANGE", "Program Rule Change"),
                            ("SPECIAL_MEASURE", "Special/Temporary Measure"),
                            ("INTERNATIONAL_AGREEMENT", "International Agreement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "expected_impact",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Impact"),
                            ("MEDIUM", "Medium Impact"),
                            ("LOW", "Low Impact"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "target_change",
                    models.IntegerField(
                        blank=True, help_text="Change in immigration targets", null=True
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="drawcategory",
            name="code",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="PoolComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_candidates",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "candidates_600_plus",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "candidates_500_599",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "candidates_450_499",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "candidates_400_449",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "candidates_below_400",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("new_registrations", models.IntegerField(blank=True, null=True)),
                ("expired_profiles", models.IntegerField(blank=True, null=True)),
                ("average_crs", models.FloatField(blank=True, null=True)),
                ("median_crs", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
