# Generated by Django 4.2.16 on 2025-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_governmentcontext_pnpactivity_policyannouncement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expressentrydraw",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
