# Generated by Django 4.2.16 on 2025-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0004_update_prediction_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="precomputedprediction",
            name="predicted_date_lower",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="precomputedprediction",
            name="predicted_date_upper",
            field=models.DateField(blank=True, null=True),
        ),
    ]
