# Generated by Django 4.2.16 on 2025-08-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0005_add_date_confidence_intervals"),
    ]

    operations = [
        migrations.AddField(
            model_name="precomputedprediction",
            name="interval_type",
            field=models.CharField(
                default="CI",
                help_text="CI for frequentist, CrI for Bayesian",
                max_length=10,
            ),
        ),
    ]
